### decompose

In [1]:
import sys
sys.path.append('/media/disk1/chatgpt/zh/tabular_data')

In [2]:
import pandas as pd
from utils import parse_specific_composition, add_row_number, parse_specific_composition_zh
from langchain.chains import LLMChain
from langchain_openai import ChatOpenAI, OpenAI
from data_loader import TableFormat, TableLoader
from langchain.memory import ChatMessageHistory
from langchain_core.messages import AIMessage, HumanMessage
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.runnables.history import RunnableWithMessageHistory
from langchain_community.embeddings import HuggingFaceBgeEmbeddings
from sqlalchemy import create_engine
from executor import SQLManager
import sqlparse
embeddings = HuggingFaceBgeEmbeddings(
            model_name='BAAI/bge-large-en',
            model_kwargs={'device': 'cuda:2', 'trust_remote_code': True},
            encode_kwargs={'normalize_embeddings': True})

In [3]:
from langchain.prompts.prompt import PromptTemplate
from langchain.prompts.few_shot import FewShotPromptTemplate
from data_loader import TableFormat
query_examples = [
                  "what was the time difference between the first place finisher and the eighth place finisher?",
                  # "compare the chart positions between the us and the uk for the science of selling yourself short, where did it do better?",
                  "other than william stuart price, which other businessman was born in tulsa?",
                  "which canadian city had the most passengers traveling from manzanillo international airport in 2013?"
                # "what is the next most populous district after haridwar?",(70)
                  ]
new_query_examples = [
  # "what was the chart position of 'The Science of Selling Yourself Short' in the US?; what was the chart position of 'The Science of Selling Yourself Short' in the UK?;",
                      "what was the time for the first place finisher?; what was the time for the eighth place finisher?",
                      "was william stuart price born in tulsa?; who was born in tulsa?",
                      "how many passengers do each airline from canadian city have? which canadian city had the most passengers?"
                    # "what are the districts after haridwar?; what is the next most populous district after haridwar?",
                    #   "When did polona hercog partner with alberta brianti?; When did polona hercog partner with stephanie vogt?",
                      ]
num_k = 3
inds = [1, 11, 86, 70, 42]
table_loader = TableLoader(table_name='wikitable', split='validation', use_sample=True, small_test=False)
normalised_data = [table_loader.normalize_table(table_loader.dataset[inds[i]]) for i in range(num_k)]
example_samples = [TableFormat(format='none', data=normalised_data[i], save_embedding=True, embeddings=embeddings).get_sample_data(sample_type='embedding', query=normalised_data[i]['query']) for i in range(num_k)]
examples = [TableFormat.format_nl_sep(example_samples[i], normalised_data[i]['table']['caption']) for i in range(num_k)]

examples_prompt = PromptTemplate(input_variables=["query", "table", "new_query"], template=
"""Sub-Table: {table}
Query: {query}
Decompose query: {new_query}""")

examples_dict = [{"query": query_examples[i],
                                    "table": examples[i],
                                    "new_query": new_query_examples[i]} for i in range(num_k)]
decompose_prompt_wiki = FewShotPromptTemplate(
    examples=examples_dict,
    example_prompt=examples_prompt,
    prefix="""You are capable of converting complex query into sub queries. Based on the table, decompose original query into at most 2 complete sub queries which can solve original query. Output new query directly.""",
    suffix=
    """Sub-Table: {table}
Query: {query}
Decompose query: """,
    input_variables=["query", "table"],
)

In [4]:
task_name = 'fetaqa'
split = 'test'
model_name = 'gpt-3.5-turbo-0125'
model = ChatOpenAI(model_name=model_name, openai_api_base="https://api.chatanywhere.com.cn/v1",
                       openai_api_key="sk-WZtqZEeuE0Xb6syVghDgAxdwe0ASWLkQRGxl61UI7B9RqNC4", temperature=0.7).bind(logprobs=True)
schema_information = pd.read_csv(f"../result/aug/{task_name}_{split}_schema.csv", index_col='table_id')
aug_information = pd.read_csv(f"../result/aug/{task_name}_{split}_summary.csv", index_col='table_id')
composition_information = pd.read_csv(f"../result/aug/{task_name}_{split}_composition.csv", index_col='table_id')
engine = create_engine('sqlite:////media/disk1/chatgpt/zh/tabular_data/db/sqlite/fetaqa.db', echo=False)
manager = SQLManager(engine=engine)

In [5]:
table_loader = TableLoader(table_name=task_name, split='test', use_sample=False, small_test=False)
sample = table_loader.normalize_table(table_loader.dataset[2])

### step-back

In [6]:
from langchain.prompts.prompt import PromptTemplate
from langchain.prompts.few_shot import FewShotPromptTemplate
from data_loader import TableFormat
inds = [11,]
num_k = 1
table_loader = TableLoader(table_name='wikitable', split='validation', use_sample=True, small_test=False)
normalised_data = [table_loader.normalize_table(table_loader.dataset[inds[i]]) for i in range(num_k)]
example_samples = [TableFormat(format='none', data=normalised_data[i], save_embedding=False).get_sample_data(sample_type='random') for i in range(num_k)]
examples = [TableFormat.format_nl_sep(example_samples[i], normalised_data[i]['table']['caption']) for i in range(num_k)]
new_query_examples = [
    # "Which country uses the US dollar as its currency and has the Federal Reserve as its central bank?",
    "which business man was born in tulsa?",
    ]
examples_prompt = PromptTemplate(input_variables=["query", "new_query"], template=
"""
Query: {query}
Table: {table}
New query: {new_query}""")

examples_dict = [{"query": table_loader.dataset[inds[i]]['question'],
                  "table": examples[i],
                    "new_query": new_query_examples[i]} for i in range(num_k)]
step_back_prompt_wiki = FewShotPromptTemplate(
    examples=examples_dict,
    example_prompt=examples_prompt,
    prefix="""Based on the table, your task is to step back and paraphrase a question to a more generic step-back question, which is easier to answer.""",
    suffix=
    """
Query: {query}
Table: {table}
New query:""",
    input_variables=["query", "table"],
)

In [7]:
def get_k_shot_with_answer(k: int=1):
    sqls = ["SELECT MIN(points) FROM DF WHERE rider = 'roger dutton / tony wright';"
            ]
    thoughts = ["Based on the SQL query provided, the minimum number of points that Roger Dutton / Tony Wright received in the 1972 Isle of Man TT event was 3. 3 is the fewest points they received. "]
    tables = ["<table>\n<caption>1972 isle of man tt</caption>\n<thead>\n<tr><th>  MIN(points)</th></tr>\n</thead>\n<tbody>\n<tr><td>3            </td></tr>\n</tbody>\n</table>"]
    claims = ["was 2 be the fewest point that roger dutton / tony wright receive?"]
    # inds from test split
    examples_prompt = PromptTemplate(input_variables=["SQL", "table", "claim", "thought", "output"], template=
    """
SQL Excuted: 
```{SQL}```
Sub-table: {table}
Query: {claim}
Thought: {thought}
Answer: {output}
    """)
    examples_dict = dict(zip(["SQL", "table", "claim", "thought", "output"], [sqls[0], tables[0], claims[0], thoughts[0], '3']))
    prompt_template = FewShotPromptTemplate(
        examples=[examples_dict],
        example_prompt=examples_prompt,
        prefix="""Below is a sub-table generated by excuting the corresponding SQL. You need to understand the logic behind the SQL filtering. Think step by step and answer the question given in the query.
You should output in the following format:
Thought: your step by step thought
Answer: Only return the concise string instead of other format information. Do not repeat the question.
Below is an example.""",
        suffix=
        """
SQL Excuted: 
```{SQL}```
Sub-table: {table}
Extra information:
{information}

Query: {query}""",
        input_variables=["table", "query", "SQL", "information"],
)
    return prompt_template

In [8]:
def get_k_shot_with_aug(k: int=2):
    table_loader = TableLoader(table_name='wikitable', split='train', use_sample=True, small_test=False)
    examples_dict = []
    examples_dict.extend([{"table": '<table>\n<caption>Hoot Kloot</caption>\n<thead>\n<tr><th> Number</th><th> Title</th><th> Directed_by_</th><th> Released_</th></tr>\n</thead>\n<tbody>\n<tr><td>1  </td><td>"Kloot\'s Kounty"           </td><td>Hawley Pratt  </td><td>1973       </td></tr>\n<tr><td>2  </td><td>"Apache on the County Seat"</td><td>Hawley Pratt  </td><td>1973       </td></tr>\n<tr><td>6  </td><td>"Stirrups and Hiccups"     </td><td>Gerry Chiniquy</td><td>1973       </td></tr>\n</tbody>\n</table>',
                                        "claim": table_loader.dataset[95]['question'],
                                        "linking": "the last title -> Released_, the last title-> Number, title -> Title, sid marcus -> Directed_by_",
                                        "output": "Title, Released_, Number, Directed_by_"}])
    examples_prompt = PromptTemplate(input_variables=["table", "claim", "output", "linking"], template=
    """
    Table: {table}
    Query: {claim}
    Column linking: {linking}
    Columns: {output}""")
    prompt_template = FewShotPromptTemplate(
        examples=examples_dict,
        example_prompt=examples_prompt,
        prefix=
        """
    Based on the Table below, your task is accurately output columns related to the query or contain useful information about the query. This process involves linking similar words or semantically similar terms to columns in the Table.
    Approach this task as follows:
    Read the query thoroughly and list every possible link from query term to column in the Table. 
    Then Based on the column linking, output all useful columns at last. Make sure all columns in the link step are included and every column is in the Table.""",
    # You are a brilliant table executor with the capabilities information retrieval, table parsing, table partition and semantic understanding who can understand the structural information of the table.
    # Given the following table and query, you should output columns related to the query or contain useful information about the query. 
    # Here are some examples:""",
        suffix=
        """
    Table: {table}
    Extra information: {aug}
    
    Query: {claim}""",
        input_variables=["table", "claim", "aug"],
)
    return prompt_template

pre_instruction_schema = PromptTemplate(input_variables=["table"], template="""
Instruction: Given the following table, you will add Metadata about the columns in the table.
Metadata includes:
- Numerical: consist digits and numerical symbols like decimal points or signs.
- Char: whether column content is a text or description.
- Date: whether the column content is datetime.

You need to output all the column names with metadata in angle brackets.
Example: name<Char> launched<Date> count<Numerical>

Table: {table}
Output:
""")

In [9]:
# import os
# from langchain_openai import AzureChatOpenAI
# from utils import parse_output
# table_loader = TableLoader(table_name='wikitable', split='train', use_sample=True, small_test=False)
# summary_information = pd.read_csv(f"../result/aug/{task_name}_{split}_summary.csv", index_col='table_id')
# schema_information = pd.read_csv(f"../result/aug/{task_name}_{split}_schema.csv", index_col='table_id')
# composition_information = pd.read_csv(f"../result/aug/{task_name}_{split}_composition.csv", index_col='table_id')


# sample = table_loader.normalize_table(table_loader.dataset[110])

# # summary_aug, column_aug = summary_information.loc[sample['table']['id']]['summary'], summary_information.loc[sample['table']['id']]['column_description'] 
# # col_names, col_infos = parse_output(column_aug, pattern=r'([^<]*)<([^>]*)>')
# # extra_col_info = []
# # for i_c in range(len(col_names)):
# #     extra_col_info.append(f'{i_c + 1}. {col_names[i_c]}: {col_infos[i_c]}')
# formatter = TableFormat(format='none', data=sample)



# llm_chain = LLMChain(llm=model, prompt=get_k_shot_with_aug(), verbose=False)
# batch_pred = llm_chain.batch([{
#     "claim": sample['query'],
#     'aug':  '',
#     # "query": "how many of the seasons games were played in the gold coast convention centre?",
#                             "table": TableFormat.format_html(data= formatter.get_sample_data(sample_type='random',k=5, query=sample['query'],),table_caption=sample['table']['caption'])}],)
# print(batch_pred[0]['text'])
#     #                             "table": """table caption : 2008 - 09 nbl season.

In [10]:
from utils import parse_output
def scene_A(query, sample, k =3, verbose=True):
    row_instruction = PromptTemplate(input_variables=["table", "claim", "aug"], 
                                 template="""Our ultimate goal is to answer query based on the original table. Now we have a sub-table with rows sampled from the original table, you are required to infer the data distribution and format from the sample data of the sub-table. Carefully analyze the query, based on the augmentation information, write a SQLITE3 SELECT SQL statement using table DF that complete query. Directly Output SQL, do not add other string.
sub-table: {table}
Extra information: {aug}

Query: {claim}
SQL: """)
    formatter = TableFormat(format='none', data=sample, save_embedding=True, embeddings=embeddings)
    k_shot_prompt = get_k_shot_with_aug()
    formatter.normalize_schema(schema_information.loc[sample['table']['id']]['schema'])
    if k == 0:
        sample_data = formatter.get_sample_data(sample_type='head', k=k)
    else:
        sample_data = formatter.get_sample_data(sample_type='embedding', query=query, k=k)
    with get_openai_callback() as cb:
        llm_chain = LLMChain(llm=model, prompt=k_shot_prompt, verbose=verbose)
        summary_aug, column_aug = aug_information.loc[sample['table']['id']]['summary'], aug_information.loc[sample['table']['id']]['column_description'] 
        col_names, col_infos = parse_output(column_aug, pattern=r'([^<]*)<([^>]*)>')
        extra_col_info = []
        for i_c in range(len(col_names)):
            extra_col_info.append(f'{i_c + 1}. {col_names[i_c]}: {col_infos[i_c]}')
        
        stage_1_batch_pred = llm_chain.batch([dict({'table': TableFormat.format_html(data=sample_data, table_caption=sample['table']['caption']),
                                            'claim': query,
                                            'aug':  summary_aug + '\n'.join(extra_col_info)
                                            })], return_only_outputs=True)[0]['text']
        if verbose:
            print(stage_1_batch_pred)
        stage_1_batch_pred = stage_1_batch_pred.split(':')[-1]
        
        extra_cols = formatter.get_sample_column(embeddings, column_aug)
        # stage 2: SQL generation
        llm_chain = LLMChain(llm=model, prompt=row_instruction, verbose=verbose)
        columns = list(set([c.strip() for c in stage_1_batch_pred.split(',')] + extra_cols))
        
        try: 
            # formatter.all_data = formatter.all_data.loc[:, columns]
            sample_data = add_row_number(sample_data.loc[:, columns])
        except:
            pass
        extra_information = []
        tuples = parse_specific_composition_zh(composition_information.loc[sample['table']['id']]['composition'], sample_data.columns)
        for col, com in tuples:
            if len(pd.unique(formatter.all_data[col])) < 6:
                com += f' (Values like {", ".join(list(pd.unique(formatter.all_data[col].astype(str))))})'
                extra_information.append(col + ':' + com)
            else:
                com += f' (Values like {", ".join(list(pd.unique(formatter.all_data[col][:3].astype(str))))}...)'
                extra_information.append(col + ':' + com)
        extra_information.append('row_number: row number in the original table')
        stage_2_batch_pred = llm_chain.batch([dict({'table': TableFormat.format_html(data = sample_data, table_caption=sample['table']['caption']),
                                            'claim': query,
                                            'aug':  summary_aug + '\nColumn information:\n' + '\n'.join(extra_information)
                                            })], return_only_outputs=True)[0]['text'].replace("–", "-").replace("—", "-").replace("―", "-").replace("−", "-")
        if verbose:
            print(stage_2_batch_pred)
    # stage 3: SQL Excution
    try: 
        execute_data = manager.execute_from_df(stage_2_batch_pred, add_row_number(formatter.all_data), table_name='DF')
    except:
        execute_data = formatter.all_data
        stage_2_batch_pred = 'SELECT * from DF;'
    if len(execute_data) == 0:
        return query, stage_2_batch_pred, 'No data from database', cb.total_tokens
    return query, stage_2_batch_pred, TableFormat.format_html(data=execute_data), cb.total_tokens

In [11]:
import concurrent.futures
from langchain_community.callbacks import get_openai_callback
def parallel_run(func, args_list):
    with concurrent.futures.ThreadPoolExecutor() as executor:
        results = [executor.submit(func, arg) for arg in args_list]
        return [future.result() for future in concurrent.futures.as_completed(results)]

def parallel_run_kwargs(func, args_list):
    with concurrent.futures.ThreadPoolExecutor() as executor:
        results = executor.map(lambda kwargs: func(**kwargs), args_list)
        return list(results)

### RUN

In [12]:
def eval_blury_string(pred_list):
    pred_label = []
    for pred in pred_list:
        predict_ans = pred.split('\n')[-1]
        if '0' in predict_ans:
            predict_ans = '0'
        elif '1' in predict_ans:
            predict_ans = '1'
        else:
            predict_ans = '2'
        pred_label.append(predict_ans)
    return pred_label

In [13]:
import concurrent.futures
from typing import List
import os
import json
from langchain_community.callbacks import get_openai_callback
def parallel_run(func, args_list):
    with concurrent.futures.ThreadPoolExecutor() as executor:
        results = [executor.submit(func, arg) for arg in args_list]
        return [future.result() for future in concurrent.futures.as_completed(results)]

def parallel_run_kwargs(func, args_list):
    with concurrent.futures.ThreadPoolExecutor() as executor:
        results = executor.map(lambda kwargs: func(**kwargs), args_list)
        return list(results)

def save_csv(input_list: List[List], label_list: List, file_path):
    import pandas as pd
    directory = os.path.dirname(file_path)
    if not os.path.exists(directory):
        os.makedirs(directory)

    assert len(input_list) == len(label_list)
    df = pd.DataFrame()
    for i in range(len(label_list)):
        df[label_list[i]] = pd.Series(input_list[i])
    if os.path.exists(file_path) and file_path.endswith('.csv'):
        df_origin = pd.read_csv(file_path)
        df = pd.concat([df_origin, df], axis=0)
    df.to_csv(file_path, index=False, encoding='utf-8')

## 调整extrainformation的位置

In [14]:
from utils import parse_output
answer_instruction = PromptTemplate(input_variables=["SQL", "table", "claim"], 
                                    template="""
Below is a sub-table generated by excuting the corresponding SQL. You need to understand the logic behind the SQL filtering and answer the query using the final sub-table. 
SQL Excuted: 
```{SQL}```
Sub-table: 
{table}
Query: {claim}
Please provide a clear, complete statement in response to the query. If you cannot answer the query based on the sub-table, just say 'Cannot get answer from sub-table'.
""" )
def scene_B(query, sample, k=3, verbose=False):
    row_instruction = PromptTemplate(input_variables=["table", "claim", "aug"], 
                                 template="""Our ultimate goal is to answer query based on the original table. Now we have a sub-table with rows sampled from the original table, you are required to infer the data distribution and format from the sample data of the sub-table. Carefully analyze the query, based on the augmentation information, write a SQLITE3 SELECT SQL statement using table DF that complete query. Directly Output SQL, do not add other string.
sub-table: {table}
Extra information: {aug}

Query: {claim}
SQL: """)
    
    formatter = TableFormat(format='none', data=sample, save_embedding=True, embeddings=embeddings)
    formatter.normalize_schema(schema_information.loc[sample['table']['id']]['schema'])
    if k == 0:
        sample_data = formatter.get_sample_data(sample_type='head', k=k)
    else:
        sample_data = formatter.get_sample_data(sample_type='embedding', query=query, k=k)
    # get columns
    with get_openai_callback() as cb:
        llm_chain = LLMChain(llm=model, prompt=get_k_shot_with_aug(), verbose=verbose)
        summary_aug, column_aug = aug_information.loc[sample['table']['id']]['summary'], aug_information.loc[sample['table']['id']]['column_description'] 
        col_names, col_infos = parse_output(column_aug, pattern=r'([^<]*)<([^>]*)>')
        extra_col_info = []
        for i_c in range(len(col_names)):
            extra_col_info.append(f'{i_c + 1}. {col_names[i_c]}: {col_infos[i_c]}')
        stage_1_batch_pred = llm_chain.batch([dict({'table': TableFormat.format_html(data=sample_data, table_caption=sample['table']['caption']),
                                            'claim': query,
                                            'aug':  summary_aug + '\n'.join(extra_col_info)
                                            })], return_only_outputs=True)[0]['text']
        stage_1_batch_pred = stage_1_batch_pred.split(':')[-1]
        
        extra_cols = formatter.get_sample_column(embeddings, column_aug)
        # stage 2: SQL generation
        llm_chain = LLMChain(llm=model, prompt=row_instruction, verbose=verbose)
        columns = list(set([c.strip() for c in stage_1_batch_pred.split(',')] + extra_cols))
        
        try: 
            sample_data = add_row_number(sample_data.loc[:, columns])
        except:
            pass
        extra_information = []
        tuples = parse_specific_composition_zh(composition_information.loc[sample['table']['id']]['composition'], sample_data.columns)
        for col, com in tuples:
            if len(pd.unique(formatter.all_data[col])) < 6:
                com += f' (Values like {", ".join(list(pd.unique(formatter.all_data[col].astype(str))))})'
                extra_information.append(col + ':' + com)
            else:
                com += f' (Values like {", ".join(list(pd.unique(formatter.all_data[col][:3].astype(str))))}...)'
                extra_information.append(col + ':' + com)
        #  sample augmentation
        # extra_information = (parse_specific_composition(composition_information.loc[sample['table']['id']]['composition'], sample_data.columns))
        extra_information.append('row_number: row number in the table')
        stage_2_batch_pred = llm_chain.batch([dict({'table': TableFormat.format_html(data=sample_data, table_caption=sample['table']['caption']),
                                            'claim': query,
                                            'aug':  summary_aug + '\n Column information:' + '\n'.join(extra_information)
                                            })], return_only_outputs=True)[0]['text'].replace("–", "-").replace("—", "-").replace("―", "-").replace("−", "-")
    
        
        # stage 3: SQL Excution
        try: 
            execute_data= manager.execute_from_df(stage_2_batch_pred, add_row_number(formatter.all_data), table_name='DF')
        except:
            execute_data = formatter.all_data
            stage_2_batch_pred = 'SELECT * from DF;'
        llm_chain = LLMChain(llm=model, prompt=answer_instruction, verbose=verbose)
        response = llm_chain.batch([dict({'table': TableFormat.format_html(execute_data),
                                                'claim': query,
                                                'SQL':  stage_2_batch_pred
                                                })], return_only_outputs=True)[0]['text']
    # print("total_tokens:", cb.total_tokens)
    return response, cb.total_tokens

In [20]:
from langchain_openai import AzureChatOpenAI
import os

os.environ["AZURE_OPENAI_API_KEY"] = "2b219db0d2984f9dae28b651ab8ab3d9"
os.environ["AZURE_OPENAI_ENDPOINT"] = "https://smsh.openai.azure.com/"
os.environ["AZURE_OPENAI_API_VERSION"] = "2024-02-01"
os.environ["AZURE_OPENAI_CHAT_DEPLOYMENT_NAME"] = "gpt-35-turbo"

model = AzureChatOpenAI(
    openai_api_version=os.environ["AZURE_OPENAI_API_VERSION"],
    azure_deployment=os.environ["AZURE_OPENAI_CHAT_DEPLOYMENT_NAME"],
    temperature=0.01
)

In [21]:
from langchain.chains import LLMChain
from langchain_openai import ChatOpenAI, OpenAI
import datetime
from FlagEmbedding import FlagReranker
from openai import BadRequestError
from tqdm.notebook import tqdm
table_loader = TableLoader(table_name='fetaqa', split='test', use_sample=False, small_test=False)
# model = ChatOpenAI(model_name='gpt-3.5-turbo-0125', openai_api_base="https://api.chatanywhere.com.cn/v1",
#                        openai_api_key="sk-WZtqZEeuE0Xb6syVghDgAxdwe0ASWLkQRGxl61UI7B9RqNC4", temperature=0.01)
# save_path = f"../result/answer/fetaqa_{datetime.datetime.now().strftime('%m-%d_%H-%M-%S')}.csv"
save_path = f"../result/answer/fetaqa_05-23_03-13-17.csv"

# reranker = FlagReranker('BAAI/bge-reranker-large', use_fp16=True)

muilti_answer_instruction = PromptTemplate(input_variables=["information", "claim"], 
# template="""You are a brilliant table executor with the capabilities information retrieval, table parsing, table partition and semantic understanding who can understand the structural information of the table.
template = """
Below is a sub-table generated by excuting the corresponding SQL. You need to understand the logic behind the SQL filtering.
Query: {query}
SQL Excuted: 
```{SQL}```
Sub-table:
{table}
Extra information:
{information}
Answer the query according to the information given. Only return the string instead of other format information.
""" )
sample_k = 3
# Task: answer the last question given in the query. Only return the string instead of other format information. Do not repeat the question.
# Task: verify whether the provided claim/query is true or false, return 0 if it's false, or 1 if it's true. Please think step by step and return 0/1 at last.


# muilti_answer_instruction = get_k_shot_with_answer()
# for sample_n in range(3):
tokens = []
outputs = []
labels = []
ids = []
extra_quries = []
i = 860
with tqdm(total=len(table_loader.dataset) - 730, desc=f"Processing",ncols=1000) as pbar:
    while i < len(table_loader.dataset):
        try:
            sample = table_loader.normalize_table(
                                table_loader.dataset[i])
            
            all_tokens = 0
            all_queries = []
            formatter = TableFormat(format='none', data=sample, save_embedding=False)
            if len(formatter.all_data) == 0:
                i +=1
                pbar.update(1)
                continue
            sample_data = formatter.get_sample_data(sample_type='random', k=sample_k, query=sample['query'])
            with get_openai_callback() as cb:
                llm_chain = LLMChain(llm=model, prompt=step_back_prompt_wiki, verbose=False)
                batch_pred = llm_chain.batch([{"query": sample['query'], "table": TableFormat.format_html(sample_data)}], return_only_outputs=True)
                all_queries.append(batch_pred[0]['text'].strip())
                llm_chain = LLMChain(llm=model, prompt=decompose_prompt_wiki, verbose=False)
                batch_pred = llm_chain.batch([{"query": sample['query'], "table": TableFormat.format_html(sample_data)}], return_only_outputs=True)
                all_queries.extend(batch_pred[0]['text'].split(';'))
                # print(all_queries)
            all_tokens += cb.total_tokens
            all_queries = list(set(all_queries))
            args_list = [{"query": q, "sample": sample, "k": sample_k} for q in all_queries]
            # print(args_list)
            ans_from_B = parallel_run_kwargs(scene_B, args_list)
            results = [res[0] for res in ans_from_B if 'Cannot get answer from sub-table' not in res[0] ]
            all_tokens += sum([res[1] for res in ans_from_B])
            #With answer
            # results= []
            with get_openai_callback() as cb:
                imp_input = scene_A(sample['query'], sample, sample_k, False)
                llm_chain = LLMChain(llm=model, prompt=muilti_answer_instruction , verbose=False)
                batch_pred = llm_chain.batch([{"query": sample['query'],"SQL": imp_input[1], "table": imp_input[2], "information": '\n'.join(results)}], return_only_outputs=True)
            # print(batch_pred[0])
            all_tokens += cb.total_tokens
            # print('ALL TOKENS', all_tokens)
            ids.append(sample['id'])
            labels.append(sample['query'])
            outputs.append(batch_pred[0]['text'])
            tokens.append(all_tokens)
            extra_quries.append(';'.join(all_queries))
            if (i + 1) % 10 == 0:
                    print(f'saving {i}')
                    save_csv([outputs, labels, ids, tokens, extra_quries], ['preds', 'statements','ids', 'tokens', 'extra'], file_path=save_path)
                    outputs = []
                    labels = []
                    ids = []
                    tokens = []
                    extra_quries = []
            i += 1
            pbar.update(1)
        except ValueError as e:
            print(f'******************Value Error {i}****************************')
            i += 1
            pbar.update(1)
        except BadRequestError as e:
            print('*************************Bad Request**************')
            i += 1
            pbar.update(1)

Processing:   0%|                                                                                             …

saving 869
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
saving 879
saving 889
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
saving 899
Unknown Date format 0    Warm Up Tour
1    23 June 2013
2    Album Launch
3    17 July 2013
4    18 July 2013
Name: Date, dtype: object
Unknown Date format 0    Warm Up Tour
1    23 June 2013
2    Album Launch
3    17 July 2013
4    18 July 2013
Name: Date, dtype: object
Unknown Date format 0    Warm Up Tour
1    23 June 2013
2    Album Launch
3    17 July 2013
4    18 July 2013
Name: Date, dtype: object
Unknown Date format 0    Warm Up Tour
1    23 June 2013
2    Album Launch
3    17 July 2013
4    18 July 2013
Name: Date, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
saving 909
Unknown Date format 0       August 17, 2006
1       August 21, 2007
2       October 1, 2008
3    September 16, 2009
4    September 15, 2010
Name: Finale, dtype: object
Unknown Date format 0       August 17, 2006
1       August 21, 2007
2       October 1, 2008
3    September 16, 2009
4    September 15, 2010
Name: Finale, dtype: object
Unknown Date format 0       August 17, 2006
1       August 21, 2007
2       October 1, 2008
3    September 16, 2009
4    September 15, 2010
Name: Finale, dtype: object
saving 919
Unknown Date format 0               Majority
1                Turnout
2    Registered electors
Name: Candidate, dtype: object
Unknown Date format 0               Majority
1                Turnout
2    Registered electors
Name: Candidate, dtype: object
Unknown Date format 0               Majority
1                Turnout
2    Registered electors
Name: Candidate, dtype: object
saving 929
saving 939
saving 949
Unknown Date format 0      June 23 - July 2
1      June 22 - July 3
2            June 20-30
3            June 19-29
4    July 30 - August 9
Name: Dates, dtype: object
Unknown Date format 0      June 23 - July 2
1      June 22 - July 3
2            June 20-30
3            June 19-29
4    July 30 - August 9
Name: Dates, dtype: object
Unknown Date format 0      June 23 - July 2
1      June 22 - July 3
2            June 20-30
3            June 19-29
4    July 30 - August 9
Name: Dates, dtype: object
saving 959
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
saving 969
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
saving 979
Unknown Date format 0    October 6, 1871
1                  -
2                  -
3       May 15, 1876
4       May 15, 1876
Name: Date_opened, dtype: object
Unknown Date format 0                -
1                -
2                -
3          c. 1901
4    June 17, 1906
Name: Date_closed, dtype: object
Unknown Date format 0    October 6, 1871
1                  -
2                  -
3       May 15, 1876
4       May 15, 1876
Name: Date_opened, dtype: object
Unknown Date format 0                -
1                -
2                -
3          c. 1901
4    June 17, 1906
Name: Date_closed, dtype: object
Unknown Date format 0    October 6, 1871
1                  -
2                  -
3       May 15, 1876
4       May 15, 1876
Name: Date_opened, dtype: object
Unknown Date format 0                -
1                -
2                -
3          c. 1901
4    June 17, 1906
Name: Date_closed, dtype: object
Unknown Date format 0    October 6, 1871
1                  -
2                  -
3       May 15, 1876
4       May 15, 1876
Name: Date_opened, dtype: object
Unknown Date format 0                -
1                -
2                -
3          c. 1901
4    June 17, 1906
Name: Date_closed, dtype: object
saving 989
Unknown Date format 0    1995–1998
1    1998–2000
2    2000–2003
3    1995–1998
4    1998–2000
Name: Years, dtype: object
Unknown Date format 0    1995–1998
1    1998–2000
2    2000–2003
3    1995–1998
4    1998–2000
Name: Years, dtype: object
Unknown Date format 0    1995–1998
1    1998–2000
2    2000–2003
3    1995–1998
4    1998–2000
Name: Years, dtype: object
Unknown Date format 0    1995–1998
1    1998–2000
2    2000–2003
3    1995–1998
4    1998–2000
Name: Years, dtype: object
saving 999
saving 1009
Unknown Date format 0    Majority
Name: Candidate, dtype: object
Unknown Date format 0    Majority
Name: Candidate, dtype: object
Unknown Date format 0    Majority
Name: Candidate, dtype: object
Unknown Date format 0    Majority
Name: Candidate, dtype: object
Unknown Date format 0    Total votes
Name: Candidate, dtype: object
Unknown Date format 0    Total votes
Name: Candidate, dtype: object
Unknown Date format 0    Total votes
Name: Candidate, dtype: object
Unknown Date format 0    Total votes
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Rejected ballots
1             Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Rejected ballots
1             Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Rejected ballots
1             Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Rejected ballots
1             Turnout
Name: Candidate, dtype: object
saving 1019
Unknown Date format 0    Total votes
Name: Candidate, dtype: object
Unknown Date format 0    Total votes
Name: Candidate, dtype: object
Unknown Date format 0    Total votes
Name: Candidate, dtype: object
Unknown Date format 0    Total votes
Name: Candidate, dtype: object
saving 1029
Unknown Date format 0    December 31, 1984
1    November 11, 1992
2       March 22, 1993
3    December 31, 2008
4    December 31, 2015
Name: Left_office, dtype: object
Unknown Date format 0    December 31, 1984
1    November 11, 1992
2       March 22, 1993
3    December 31, 2008
4    December 31, 2015
Name: Left_office, dtype: object
Unknown Date format 0    December 31, 1984
1    November 11, 1992
2       March 22, 1993
3    December 31, 2008
4    December 31, 2015
Name: Left_office, dtype: object
Unknown Date format 0    December 31, 1984
1    November 11, 1992
2       March 22, 1993
3    December 31, 2008
4    December 31, 2015
Name: Left_office, dtype: object
saving 1039
Unknown Date format 0         North America
1     September 3, 2011
2     September 4, 2011
3     September 7, 2011
4    September 11, 2011
Name: Date, dtype: object
Unknown Date format 0         North America
1     September 3, 2011
2     September 4, 2011
3     September 7, 2011
4    September 11, 2011
Name: Date, dtype: object
Unknown Date format 0         North America
1     September 3, 2011
2     September 4, 2011
3     September 7, 2011
4    September 11, 2011
Name: Date, dtype: object
Unknown Date format 0         North America
1     September 3, 2011
2     September 4, 2011
3     September 7, 2011
4    September 11, 2011
Name: Date, dtype: object
saving 1049
saving 1059
Unknown Date format 0          6 June 1950
1    12 September 1957
2          2 July 1960
3         20 June 1961
4       16 August 1968
Name: Left_office, dtype: object
Unknown Date format 0          6 June 1950
1    12 September 1957
2          2 July 1960
3         20 June 1961
4       16 August 1968
Name: Left_office, dtype: object
Unknown Date format 0          6 June 1950
1    12 September 1957
2          2 July 1960
3         20 June 1961
4       16 August 1968
Name: Left_office, dtype: object
saving 1069
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
saving 1079
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
saving 1089
saving 1099
Unknown Date format 0               Majority
1    Registered electors
2                Turnout
3       Rejected ballots
Name: Candidate, dtype: object
Unknown Date format 0               Majority
1    Registered electors
2                Turnout
3       Rejected ballots
Name: Candidate, dtype: object
Unknown Date format 0               Majority
1    Registered electors
2                Turnout
3       Rejected ballots
Name: Candidate, dtype: object
saving 1109
Unknown Date format 0                 Candidate
1             Horacio Serpa
2    Andrés Pastrana Arango
3               Noemí Sanín
4     Harold Bedoya Pizarro
Name: Candidate, dtype: object
Unknown Date format 0                 Candidate
1             Horacio Serpa
2    Andrés Pastrana Arango
3               Noemí Sanín
4     Harold Bedoya Pizarro
Name: Candidate, dtype: object
Unknown Date format 0                 Candidate
1             Horacio Serpa
2    Andrés Pastrana Arango
3               Noemí Sanín
4     Harold Bedoya Pizarro
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
saving 1119
Unknown Date format 0         Europe
1    27 May 2000
2    29 May 2000
3    3 June 2000
4    4 June 2000
Name: Date, dtype: object
Unknown Date format 0         Europe
1    27 May 2000
2    29 May 2000
3    3 June 2000
4    4 June 2000
Name: Date, dtype: object
Unknown Date format 0         Europe
1    27 May 2000
2    29 May 2000
3    3 June 2000
4    4 June 2000
Name: Date, dtype: object
Unknown Date format 0         Europe
1    27 May 2000
2    29 May 2000
3    3 June 2000
4    4 June 2000
Name: Date, dtype: object
saving 1129
saving 1139
Unknown Date format 0                     Invalid/blank votes
1               Registered voters/turnout
2    Source: National Election Commission
Name: Candidate, dtype: object
Unknown Date format 0                     Invalid/blank votes
1               Registered voters/turnout
2    Source: National Election Commission
Name: Candidate_1, dtype: object
Unknown Date format 0                     Invalid/blank votes
1               Registered voters/turnout
2    Source: National Election Commission
Name: Candidate, dtype: object
Unknown Date format 0                     Invalid/blank votes
1               Registered voters/turnout
2    Source: National Election Commission
Name: Candidate_1, dtype: object
Unknown Date format 0                     Invalid/blank votes
1               Registered voters/turnout
2    Source: National Election Commission
Name: Candidate, dtype: object
Unknown Date format 0                     Invalid/blank votes
1               Registered voters/turnout
2    Source: National Election Commission
Name: Candidate_1, dtype: object
Unknown Date format 0                     Invalid/blank votes
1               Registered voters/turnout
2    Source: National Election Commission
Name: Candidate, dtype: object
Unknown Date format 0                     Invalid/blank votes
1               Registered voters/turnout
2    Source: National Election Commission
Name: Candidate_1, dtype: object
saving 1149
saving 1159
Unknown Date format 0    Total votes
1        Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Total votes
1        Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Total votes
1        Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Total votes
1        Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
saving 1169
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
saving 1179
Unknown Date format 0        8 March 1967
1    25 November 1967
2      23 August 1968
3    17 February 1969
4       27 March 1970
Name: Term_of_office_1, dtype: object
Unknown Date format 0           127 days
1           262 days
2           272 days
3           178 days
4    1 year, 38 days
Name: Term_of_office_2, dtype: object
Unknown Date format 0        8 March 1967
1    25 November 1967
2      23 August 1968
3    17 February 1969
4       27 March 1970
Name: Term_of_office_1, dtype: object
Unknown Date format 0           127 days
1           262 days
2           272 days
3           178 days
4    1 year, 38 days
Name: Term_of_office_2, dtype: object
Unknown Date format 0        8 March 1967
1    25 November 1967
2      23 August 1968
3    17 February 1969
4       27 March 1970
Name: Term_of_office_1, dtype: object
Unknown Date format 0           127 days
1           262 days
2           272 days
3           178 days
4    1 year, 38 days
Name: Term_of_office_2, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0     17 January 1998
1    25 February 2001
2        7 March 1997
3    11 February 1996
4    13 February 1999
Name: Date, dtype: object
Unknown Date format 0     17 January 1998
1    25 February 2001
2        7 March 1997
3    11 February 1996
4    13 February 1999
Name: Date, dtype: object
Unknown Date format 0     17 January 1998
1    25 February 2001
2        7 March 1997
3    11 February 1996
4    13 February 1999
Name: Date, dtype: object
saving 1189
saving 1199
saving 1209
Unknown Date format 0       Leeza Gibbons
1      Geraldo Rivera
2       Vivica A. Fox
3    Brandi Glanville
4        Johnny Damon
Name: Candidate, dtype: object
Unknown Date format 0       Leeza Gibbons
1      Geraldo Rivera
2       Vivica A. Fox
3    Brandi Glanville
4        Johnny Damon
Name: Candidate, dtype: object
Unknown Date format 0       Leeza Gibbons
1      Geraldo Rivera
2       Vivica A. Fox
3    Brandi Glanville
4        Johnny Damon
Name: Candidate, dtype: object
Unknown Date format 0       Leeza Gibbons
1      Geraldo Rivera
2       Vivica A. Fox
3    Brandi Glanville
4        Johnny Damon
Name: Candidate, dtype: object
saving 1219
Unknown Date format 0                           May 12, 1999
1                           May 12, 1999
2    February 28, 2001 February 28, 2016
3    February 28, 2001 February 28, 2016
4                         September 2008
Name: Date, dtype: object
Unknown Date format 0                           May 12, 1999
1                           May 12, 1999
2    February 28, 2001 February 28, 2016
3    February 28, 2001 February 28, 2016
4                         September 2008
Name: Date, dtype: object
Unknown Date format 0                           May 12, 1999
1                           May 12, 1999
2    February 28, 2001 February 28, 2016
3    February 28, 2001 February 28, 2016
4                         September 2008
Name: Date, dtype: object
Unknown Date format 0                           May 12, 1999
1                           May 12, 1999
2    February 28, 2001 February 28, 2016
3    February 28, 2001 February 28, 2016
4                         September 2008
Name: Date, dtype: object
saving 1229
saving 1239
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
saving 1249
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
saving 1259
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
saving 1269
saving 1279
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
saving 1289
Unknown Date format 0    Majority
Name: Candidate, dtype: object
Unknown Date format 0    Majority
Name: Candidate, dtype: object
Unknown Date format 0    Majority
Name: Candidate, dtype: object
Unknown Date format 0    Majority
Name: Candidate, dtype: object
saving 1299
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
Unknown Date format 0    Majority
1     Turnout
Name: Candidate, dtype: object
saving 1309
Unknown Date format 0               Dec 2008
1    Dec 2008 – Feb 2009
2           Apr–May 2009
3          Jul–Sept 2009
4              Sept 2009
Name: Date, dtype: object
Unknown Date format 0               Dec 2008
1    Dec 2008 – Feb 2009
2           Apr–May 2009
3          Jul–Sept 2009
4              Sept 2009
Name: Date, dtype: object
Unknown Date format 0               Dec 2008
1    Dec 2008 – Feb 2009
2           Apr–May 2009
3          Jul–Sept 2009
4              Sept 2009
Name: Date, dtype: object
Unknown Date format 0               Dec 2008
1    Dec 2008 – Feb 2009
2           Apr–May 2009
3          Jul–Sept 2009
4              Sept 2009
Name: Date, dtype: object
Unknown Date format 0                     Risto Ryti
1               Väinö Kotilainen
2          Kaarlo Juho Ståhlberg
3    Carl Gustaf Emil Mannerheim
4                    Arvo Manner
Name: Candidate, dtype: object
Unknown Date format 0                     Risto Ryti
1               Väinö Kotilainen

In [19]:
i

865

In [ ]:
print(all_queries)
ans_from_B

['What were the total votes for each candidate?', 'How did the candidates perform in the election?', ' How many votes did Napolitano receive compared to the total votes for all candidates?']

[('Based on the sub-table, we cannot get an answer to the query.', 1413),
 ('Esperanza Spalding won the Jazz Artist of the Year award in 2011.', 1419),
 ('Esperanza Spalding won the Jazz Artist of the Year award at the Boston Music Awards in 2011.',
  1662)]

In [ ]:
scene_B('What were the total votes for each candidate?', sample, True)

AttributeError: 'TableFormat' object has no attribute 'db'

In [ ]:
import evaluate
bleu = evaluate.load("bleu")

Downloading builder script:   0%|          | 0.00/5.94k [00:00<?, ?B/s]

Downloading extra modules:   0%|          | 0.00/1.55k [00:00<?, ?B/s]

Downloading extra modules:   0%|          | 0.00/3.34k [00:00<?, ?B/s]

In [ ]:
from rouge import Rouge
import evaluate
bleu = evaluate.load("bleu")
reference = [sample['label']]
candidate= outputs
rouge = Rouge()
rouge_score = rouge.get_scores(hyps=candidate, refs=reference)  
results = bleu.compute(predictions=candidate, references=reference)
print(results)
print(rouge_score[0]["rouge-1"])
print(rouge_score[0]["rouge-2"])
print(rouge_score[0]["rouge-l"])

{'bleu': 0.4071220775553065, 'precisions': [0.625, 0.4, 0.35714285714285715, 0.3076923076923077], 'brevity_penalty': 1.0, 'length_ratio': 1.3333333333333333, 'translation_length': 16, 'reference_length': 12}
{'r': 0.8181818181818182, 'p': 0.8181818181818182, 'f': 0.8181818131818183}
{'r': 0.6, 'p': 0.6, 'f': 0.5999999950000001}
{'r': 0.7272727272727273, 'p': 0.7272727272727273, 'f': 0.7272727222727273}

In [ ]:
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
sentence_bleu(sample['label'].split(), outputs[0].split(), weights=(0.25, 0.25, 0.25, 0.25))

0

In [ ]:
bleu.compute(predictions=['The track with the lowest BPM on the Speed SFX series is "Mission: Impossible Theme" with a BPM of 175, and the track with the highest BPM on the Speed SFX series is also "Mission: Impossible Theme" with a BPM of 195.'], references=["The Speed SFX's lowest bpm is 175 on tracks #5–16, and the highest bpm is 195 on #20 in the Speed series."])

{'bleu': 0.0,
 'precisions': [0.34, 0.08163265306122448, 0.020833333333333332, 0.0],
 'brevity_penalty': 1.0,
 'length_ratio': 1.9230769230769231,
 'translation_length': 50,
 'reference_length': 26}

In [ ]:
46: west berkshire brewery 's maggs magnificent mild be its most decorate beer between 1995 and 2009

SyntaxError: unterminated string literal (detected at line 1) (4231422701.py, line 1)

In [ ]:
##### add residual 

from langchain.chains import LLMChain
from langchain_openai import ChatOpenAI, OpenAI
import datetime
# from FlagEmbedding import FlagReranker
from openai import BadRequestError, RateLimitError
from tqdm.notebook import tqdm
table_loader = TableLoader(table_name='wikitable', split='test', use_sample=False, small_test=False)
model = ChatOpenAI(model_name='gpt-3.5-turbo-0125', openai_api_base="https://api.chatanywhere.tech/v1",
                       openai_api_key="sk-bLZSHx4pKfPRZkYyIyyvUHSEjrlqj5sh2QIsxOM23yJnyoGD", temperature=0.01)
save_path = f"../result/answer/wikitable_query_gpt35_0301.csv"

data = pd.read_csv(save_path)

tokens = []
outputs = []
labels = []
ids = []
extra_quries = []
i = 0
with tqdm(total=200 desc=f"Processing",ncols=150) as pbar:
    while i < len(table_loader.dataset):
        if i in list(data['ids']):
            i += 1
        else:
            try:
                sample = table_loader.normalize_table(
                                    table_loader.dataset[i])
                all_tokens = 0
                all_queries = []
                formatter = TableFormat(format='none', data=sample, save_embedding=True, embeddings=embeddings)
                sample_data = formatter.get_sample_data(sample_type='random', query=sample['query'])
                with get_openai_callback() as cb:
                    llm_chain = LLMChain(llm=model, prompt=step_back_prompt_wiki, verbose=False)
                    batch_pred = llm_chain.batch([{"query": sample['query'], "table": TableFormat.format_html(sample_data)}], return_only_outputs=True)
                    all_queries.append(batch_pred[0]['text'].strip())
                    # print(all_queries)
                    llm_chain = LLMChain(llm=model, prompt=decompose_prompt_wiki, verbose=False)
                    batch_pred = llm_chain.batch([{"query": sample['query'], "table": TableFormat.format_html(sample_data)}], return_only_outputs=True)
                    all_queries.extend(batch_pred[0]['text'].split(';'))
                    # print(all_queries)
                all_tokens += cb.total_tokens
                all_queries = list(set(all_queries))
                args_list = [{"query": q, "sample": sample} for q in all_queries]
                # print(len(args_list))
                ans_from_B = parallel_run_kwargs(scene_B, args_list)
                results = [res[0] for res in ans_from_B if 'Cannot get answer from sub-table' not in res[0]]
                all_tokens += sum([res[1] for res in ans_from_B])
                #With answer
                # results= []
                with get_openai_callback() as cb:
                    imp_input = scene_A(sample['query'], sample, False)
                    llm_chain = LLMChain(llm=model, prompt=get_k_shot_with_answer() , verbose=False)
                    batch_pred = llm_chain.batch([{"query":sample['query'],"SQL": imp_input[1], "table": imp_input[2], "information": '\n'.join(results)}], return_only_outputs=True)
                    # print(batch_pred[0])
                all_tokens += cb.total_tokens
                # print('ALL TOKENS', all_tokens)
                ids.append(i)
                labels.append(sample['query'])
                outputs.append(batch_pred[0]['text'])
                tokens.append(all_tokens)
                extra_quries.append(';'.join(all_queries))
                i += 1
            #         if (i + 1) % 10 == 0:
            #                 print(f'saving {i}')

            #         i += 1
            #         pbar.update(1)
            # except ValueError as e:
            #     print(f'******************Value Error {i}****************************')
            #     i += 1
            #     pbar.update(1)
            # except BadRequestError as e:
            #     print('*************************Bad Request**************')
            #     i += 1
            #     pbar.update(1)
            except RateLimitError as e:
                print('*************************Rate limit**************')
                pass
        pbar.update(1)
# save_csv([outputs, labels, ids, tokens, extra_quries], ['preds', 'statements','ids', 'tokens', 'extra'], file_path=save_path)

SyntaxError: invalid character '：' (U+FF1A) (3998830562.py, line 1)

In [ ]:
from rouge import Rouge
reference = ['The Vietnamese Fatherland Front won 424 seats with 100% of the votes.']
candidate= ['In the 1975 North Vietnamese legislative election, the Vietnamese Fatherland Front won all 424 seats.']
rouge = Rouge()
rouge_score = rouge.get_scores(hyps=candidate, refs=reference)  
print(rouge_score[0]["rouge-1"])
print(rouge_score[0]["rouge-2"])
print(rouge_score[0]["rouge-l"])

{'r': 0.5833333333333334, 'p': 0.5384615384615384, 'f': 0.559999995008}
{'r': 0.36363636363636365, 'p': 0.2857142857142857, 'f': 0.31999999507200005}
{'r': 0.5, 'p': 0.46153846153846156, 'f': 0.47999999500800006}

In [ ]:
def parse_extra_info(summary_aug, column_aug, composition_aug, columns):
    col_names, col_infos = parse_output(column_aug, pattern=r'([^<]*)<([^>]*)>')
    items, crackets = parse_output(composition_aug, pattern = r'\d. (.+?): (.+)')
    assert len(items) == len(col_names)
    extra_col_info = []
    for i_c in range(len(col_names)):
        if col_names[i_c] in columns:
            extra_col_info.append(f'{i_c + 1}. {col_names[i_c]}: {col_infos[i_c]} {crackets[i_c]}')
            
    extra_col_info.append('row_number: row number in the original table')
    return summary_aug + '\n'.join(extra_col_info)